//! Validation hook generated by `#[derive(TptEntity)]`.

use thiserror::Error;

/// Error returned by [`Validatable::validate`].
#[derive(Debug, Error, PartialEq, Eq)]
pub enum ValidationError {
    #[error("field `{0}` is required but was empty")]
    Required(&'static str),

    #[error("field `{0}` length {1} is outside range {2}..={3}")]
    Length(&'static str, usize, usize, usize),

    #[error("field `{0}` value {1} is outside range {2}..={3}")]
    Range(&'static str, String, String, String),

    #[error("field `{0}` is not a valid email address")]
    Email(&'static str),

    #[error("validation failed: {0}")]
    Custom(&'static str),
}

/// Implemented by the `TptEntity` derive. Called before insert/update so invalid
/// entities never reach the database.
pub trait Validatable {
    /// Validate this entity. Returns the first error encountered.
    fn validate(&self) -> Result<(), ValidationError>;
}
