{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-ingestion
  labels:
    app.kubernetes.io/name: tpt-erp-ingestion
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-ingestion
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- with .Values.autoscaling.targetMetric }}
    - type: {{ .type }}
      pods:
        metric:
          name: {{ .pods.metric.name }}
        target:
          type: {{ .pods.target.type }}
          averageValue: {{ .pods.target.averageValue }}
    {{- end }}
{{- end }}
